#!/usr/bin/env bash
#transfers a file form client to server


if [ "$#" -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path="$1"
ip="$2"
username="$3"
ssh_key="$4"

scp -i "$ssh_key" "$path" "$username"@"$ip":~/ -o strictHostKeyChecking=no
