#!/usr/bin/env bash
#transfers a file form client to server

path="$1"
ip="$2"
username="$3"
p_key="$4"

echo "StrictHostKeyChecking no" >> ~/.ssh/config

if [ "$#" -lt 3 ];
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$p_key" "$path" "$username"@"$ip":~/
fi
