#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
sudo apt-get install -y haproxy

# edit config file
echo "
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 495807-web-01 54.157.181.23 check
        server 495807-web-02 34.202.157.18 check
" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
