#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"

# Function to handle SIGTERM
sigterm() {
    echo "I hate the kill command"
    cleanup_and_exit
}

# Function to handle SIGINT
sigint() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT
sigquit() {
    cleanup_and_exit
}

cleanup_and_exit() {
    rm -f "$pid_file"
    exit 0
}

echo $$ > "$pid_file"

trap 'sigterm' SIGTERM
trap 'sigint' SIGINT
trap 'sigquit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
