#!/usr/bin/env bash
# manages manage_my_process
case "$1" in
    start)
	touch /var/run/my_process.pid
	echo $$ >> /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    stop)
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    restart)
	rm -f /var/run/my_process.pid
	./manage_my_process
	touch /var/run/my_process.pid
	echo $$ >> /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
	;;
esac

exit 0
