#!/usr/bin/env bash
# displays to infinity and beyond indefinitely

on_sigterm(){
    echo "I am invincible!!!"
}

while ((1))
do
    trap 'on_sigterm' SIGTERM
    echo "To infinity and beyond indefinitely"
    sleep 2
done
