#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using
# the while loop + IFS.

while IFS=: read -r USRNAME PWD USR_ID GRP_ID USER_ID_INFO HOME_DIR CMD_SHELL
do
    echo "The user $USRNAME is part of the $GRP_ID gang, lives in $HOME_DIR"\
	 "and rides $CMD_SHELL. $USR_ID's place is protected by the passcode"\
	 "$PWD, more info about the user here: $USER_ID_INFO"
done < /etc/passwd
