#!/usr/bin/env bash
# This script  displays Best School 10 times, but for the 9th
# iteration, displays Best School and then Hi on a new line.

i=1

while [ $i -le 10 ]
do
	if [ $i -le 9 ]
	then
	   echo "Best School"
	else
	    echo "Hi"
	fi
	i=$(( i+1 ))
done
