#!/usr/bin/env bash
# whoami

username="$1"

# Create the user without prompting
sudo useradd "$username" && \
echo "$username:password" | sudo chpasswd

# Switch to the new user and execute the command
sudo su - "$username" -c whoami
